# Generated by Django 4.2 on 2023-04-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Starter', 'starter'), ('Main', 'main'), ('Dessert', 'dessert')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='menu')),
                ('description', models.TextField()),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('SINGLE', '1 adult'), ('COUPLE', '2 adults'), ('FAMILY', '2 adults & 2 children'), ('BIG_FAMILY', '4 adults')], default='COUPLE', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Energy(kcal)', 'calories'), ('Energy(kJ)', 'joules'), ('Fat', 'fat'), ('Carbohydrate', 'carbohydrate'), ('of which sugars', 'sugars'), ('Protein', 'protein'), ('Salt', 'salt')], max_length=20)),
                ('figure', models.FloatField()),
                ('unit', models.CharField(choices=[('kcal', 'kilocalorie'), ('kj', 'kilojoule'), ('g', 'gram')], max_length=5)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='ingredient')),
                ('menu', models.ManyToManyField(to='menu.menu')),
            ],
        ),
    ]
